{{ if .Values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: {{ template "nfs-subdir-external-provisioner.name" . }}
    chart: {{ template "nfs-subdir-external-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.storageClass.name }}
{{- if .Values.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ template "nfs-subdir-external-provisioner.provisionerName" . }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
parameters:
  archiveOnDelete: "{{ .Values.storageClass.archiveOnDelete }}"
  {{- if .Values.storageClass.pathPattern }}
  pathPattern: "{{ .Values.storageClass.pathPattern }}"
  {{- end }}
{{- if .Values.nfs.mountOptions }}
mountOptions:
  {{- range .Values.nfs.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
{{ end -}}
